package one.xis.e2e;

import org.junit.jupiter.api.Test;

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

class ExpressionLanguageE2ETest extends BootAppE2ETest {

    @Test
    void rendersTextExpressions() {
        openExpressionPage();

        assertThat(page.locator("#headline")).hasText("Expression Language");
        assertThat(page.locator("#user-summary")).hasText("Ada has role admin");
        assertThat(page.locator("#computed-key")).hasText("First");
        assertThat(page.locator("#ternary")).hasText("enabled");
    }

    @Test
    void rendersAttributeExpressions() {
        openExpressionPage();

        assertThat(page.locator("#user-summary")).hasAttribute("title", "Generated by EL");
        assertThat(page.locator("#user-summary")).hasAttribute("data-user", "Ada");
    }

    @Test
    void evaluatesConditionalExpressions() {
        openExpressionPage();

        assertThat(page.locator("#visible-section")).isVisible();
        assertThat(page.locator("#hidden-section")).hasCount(0);
        assertThat(page.locator("#comparison-section")).isVisible();
        assertThat(page.locator("#tag-if-section")).isVisible();
    }

    @Test
    void evaluatesBuiltInFunctions() {
        openExpressionPage();

        assertThat(page.locator("#default-value")).hasText("fallback");
        assertThat(page.locator("#joined-items")).hasText("alpha, beta, gamma");
    }

    @Test
    void evaluatesForeachExpressions() {
        openExpressionPage();

        assertThat(page.locator("#tag-items .tag-item")).hasCount(3);
        assertThat(page.locator("#tag-items .tag-item").nth(0)).hasText("Keyboard");
        assertThat(page.locator("#tag-items .tag-item").nth(1)).hasText("Mouse");
        assertThat(page.locator("#tag-items .tag-item").nth(2)).hasText("Monitor");
        assertThat(page.locator("#tag-items .tag-item").nth(2)).hasAttribute("data-id", "p3");

        assertThat(page.locator("#attribute-items .attribute-item")).hasCount(3);
        assertThat(page.locator("#attribute-items .attribute-item").nth(0)).hasText("alpha");
        assertThat(page.locator("#attribute-items .attribute-item").nth(1)).hasText("beta");
        assertThat(page.locator("#attribute-items .attribute-item").nth(2)).hasText("gamma");
    }

    @Test
    void navigatesToExpressionPageFromIndex() {
        navigateTo("/index.html");

        page.locator("#nav-expression").click();

        assertThat(page.locator("#headline")).hasText("Expression Language");
    }

    private void openExpressionPage() {
        navigateTo("/expression.html");
    }
}
