package app;

import lombok.AllArgsConstructor;
import lombok.Getter;
import one.xis.ModelData;
import one.xis.Page;

import java.util.List;
import java.util.Map;

@Page("/expression.html")
public class ExpressionPage {

    @Getter
    @AllArgsConstructor
    public static class User {
        private final String name;
        private final String role;
    }

    @Getter
    @AllArgsConstructor
    public static class Item {
        private final String id;
        private final String label;
    }

    @ModelData("headline")
    String headline() {
        return "Expression Language";
    }

    @ModelData("user")
    User user() {
        return new User("Ada", "admin");
    }

    @ModelData("tooltip")
    String tooltip() {
        return "Generated by EL";
    }

    @ModelData("visible")
    boolean visible() {
        return true;
    }

    @ModelData("hidden")
    boolean hidden() {
        return false;
    }

    @ModelData("items")
    List<String> items() {
        return List.of("alpha", "beta", "gamma");
    }

    @ModelData("lookup")
    Map<String, Item> lookup() {
        return Map.of("first_item", new Item("first", "First"));
    }

    @ModelData("prefix")
    String prefix() {
        return "first";
    }

    @ModelData("emptyValue")
    String emptyValue() {
        return "";
    }

    @ModelData("products")
    List<Item> products() {
        return List.of(
                new Item("p1", "Keyboard"),
                new Item("p2", "Mouse"),
                new Item("p3", "Monitor")
        );
    }
}
